version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: trapforge-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme123
      MYSQL_DATABASE: trapforge_logs
      MYSQL_USER: trapforge_user
      MYSQL_PASSWORD: trapforge_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: trapforge-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data: