version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: trapforge-aei-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aei123
      MYSQL_DATABASE: trapforge_logs
      MYSQL_USER: aei_user
      MYSQL_PASSWORD: aei_pass
    ports:
      - "3307:3306"
    volumes:
      - aei_mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: trapforge-aei-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  aei_mysql_data: